// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"funnel/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 触发图书馆登录，gateway 内部维护 cookie 缓存，返回 session token
				Method:  http.MethodPost,
				Path:    "/auth/library/login",
				Handler: LibraryLoginHandler(serverCtx),
			},
			{
				// 触发正方登录，gateway 内部维护 cookie 缓存，返回 session token
				Method:  http.MethodPost,
				Path:    "/auth/zf/login",
				Handler: ZfLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/library/borrow/current",
				Handler: GetCurrentBorrowHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/library/borrow/history",
				Handler: GetBorrowHistoryHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/zf/class-table",
				Handler: GetClassTableHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/zf/exam",
				Handler: GetExamInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/zf/midterm-score",
				Handler: GetMidTermScoreHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/zf/room",
				Handler: GetRoomInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/zf/score",
				Handler: GetScoreHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/funnel"),
	)
}
