// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: worker.proto

package workerzfservice

import (
	"context"

	"funnel/api/rpc/funnel"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BorrowedBook              = funnel.BorrowedBook
	Exam                      = funnel.Exam
	GetBorrowHistoryResponse  = funnel.GetBorrowHistoryResponse
	GetClassTableResponse     = funnel.GetClassTableResponse
	GetCurrentBorrowResponse  = funnel.GetCurrentBorrowResponse
	GetExamInfoResponse       = funnel.GetExamInfoResponse
	GetMidTermScoreResponse   = funnel.GetMidTermScoreResponse
	GetRoomInfoRequest        = funnel.GetRoomInfoRequest
	GetRoomInfoResponse       = funnel.GetRoomInfoResponse
	GetScoreResponse          = funnel.GetScoreResponse
	Lesson                    = funnel.Lesson
	LibraryLoginRequest       = funnel.LibraryLoginRequest
	LibraryLoginResponse      = funnel.LibraryLoginResponse
	LibrarySessionPageRequest = funnel.LibrarySessionPageRequest
	MidTermScore              = funnel.MidTermScore
	PracticeLesson            = funnel.PracticeLesson
	Room                      = funnel.Room
	Score                     = funnel.Score
	StudentInfo               = funnel.StudentInfo
	ZfLoginRequest            = funnel.ZfLoginRequest
	ZfLoginResponse           = funnel.ZfLoginResponse
	ZfSessionTermRequest      = funnel.ZfSessionTermRequest

	WorkerZfService interface {
		ZfLogin(ctx context.Context, in *ZfLoginRequest, opts ...grpc.CallOption) (*ZfLoginResponse, error)
		LibraryLogin(ctx context.Context, in *LibraryLoginRequest, opts ...grpc.CallOption) (*LibraryLoginResponse, error)
		GetScore(ctx context.Context, in *ZfSessionTermRequest, opts ...grpc.CallOption) (*GetScoreResponse, error)
		GetMidTermScore(ctx context.Context, in *ZfSessionTermRequest, opts ...grpc.CallOption) (*GetMidTermScoreResponse, error)
		GetClassTable(ctx context.Context, in *ZfSessionTermRequest, opts ...grpc.CallOption) (*GetClassTableResponse, error)
		GetExamInfo(ctx context.Context, in *ZfSessionTermRequest, opts ...grpc.CallOption) (*GetExamInfoResponse, error)
		GetRoomInfo(ctx context.Context, in *GetRoomInfoRequest, opts ...grpc.CallOption) (*GetRoomInfoResponse, error)
		GetBorrowHistory(ctx context.Context, in *LibrarySessionPageRequest, opts ...grpc.CallOption) (*GetBorrowHistoryResponse, error)
		GetCurrentBorrow(ctx context.Context, in *LibrarySessionPageRequest, opts ...grpc.CallOption) (*GetCurrentBorrowResponse, error)
	}

	defaultWorkerZfService struct {
		cli zrpc.Client
	}
)

func NewWorkerZfService(cli zrpc.Client) WorkerZfService {
	return &defaultWorkerZfService{
		cli: cli,
	}
}

func (m *defaultWorkerZfService) ZfLogin(ctx context.Context, in *ZfLoginRequest, opts ...grpc.CallOption) (*ZfLoginResponse, error) {
	client := funnel.NewWorkerZfServiceClient(m.cli.Conn())
	return client.ZfLogin(ctx, in, opts...)
}

func (m *defaultWorkerZfService) LibraryLogin(ctx context.Context, in *LibraryLoginRequest, opts ...grpc.CallOption) (*LibraryLoginResponse, error) {
	client := funnel.NewWorkerZfServiceClient(m.cli.Conn())
	return client.LibraryLogin(ctx, in, opts...)
}

func (m *defaultWorkerZfService) GetScore(ctx context.Context, in *ZfSessionTermRequest, opts ...grpc.CallOption) (*GetScoreResponse, error) {
	client := funnel.NewWorkerZfServiceClient(m.cli.Conn())
	return client.GetScore(ctx, in, opts...)
}

func (m *defaultWorkerZfService) GetMidTermScore(ctx context.Context, in *ZfSessionTermRequest, opts ...grpc.CallOption) (*GetMidTermScoreResponse, error) {
	client := funnel.NewWorkerZfServiceClient(m.cli.Conn())
	return client.GetMidTermScore(ctx, in, opts...)
}

func (m *defaultWorkerZfService) GetClassTable(ctx context.Context, in *ZfSessionTermRequest, opts ...grpc.CallOption) (*GetClassTableResponse, error) {
	client := funnel.NewWorkerZfServiceClient(m.cli.Conn())
	return client.GetClassTable(ctx, in, opts...)
}

func (m *defaultWorkerZfService) GetExamInfo(ctx context.Context, in *ZfSessionTermRequest, opts ...grpc.CallOption) (*GetExamInfoResponse, error) {
	client := funnel.NewWorkerZfServiceClient(m.cli.Conn())
	return client.GetExamInfo(ctx, in, opts...)
}

func (m *defaultWorkerZfService) GetRoomInfo(ctx context.Context, in *GetRoomInfoRequest, opts ...grpc.CallOption) (*GetRoomInfoResponse, error) {
	client := funnel.NewWorkerZfServiceClient(m.cli.Conn())
	return client.GetRoomInfo(ctx, in, opts...)
}

func (m *defaultWorkerZfService) GetBorrowHistory(ctx context.Context, in *LibrarySessionPageRequest, opts ...grpc.CallOption) (*GetBorrowHistoryResponse, error) {
	client := funnel.NewWorkerZfServiceClient(m.cli.Conn())
	return client.GetBorrowHistory(ctx, in, opts...)
}

func (m *defaultWorkerZfService) GetCurrentBorrow(ctx context.Context, in *LibrarySessionPageRequest, opts ...grpc.CallOption) (*GetCurrentBorrowResponse, error) {
	client := funnel.NewWorkerZfServiceClient(m.cli.Conn())
	return client.GetCurrentBorrow(ctx, in, opts...)
}
