// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: funnel.proto

package workerzfservice

import (
	"context"

	"funnel/apps/funnel-rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BorrowedBook              = pb.BorrowedBook
	Exam                      = pb.Exam
	GetBorrowHistoryResponse  = pb.GetBorrowHistoryResponse
	GetClassTableResponse     = pb.GetClassTableResponse
	GetCurrentBorrowResponse  = pb.GetCurrentBorrowResponse
	GetExamInfoResponse       = pb.GetExamInfoResponse
	GetMidTermScoreResponse   = pb.GetMidTermScoreResponse
	GetRoomInfoRequest        = pb.GetRoomInfoRequest
	GetRoomInfoResponse       = pb.GetRoomInfoResponse
	GetScoreResponse          = pb.GetScoreResponse
	Lesson                    = pb.Lesson
	LibraryLoginRequest       = pb.LibraryLoginRequest
	LibraryLoginResponse      = pb.LibraryLoginResponse
	LibrarySessionPageRequest = pb.LibrarySessionPageRequest
	MidTermScore              = pb.MidTermScore
	PracticeLesson            = pb.PracticeLesson
	Room                      = pb.Room
	Score                     = pb.Score
	StudentInfo               = pb.StudentInfo
	ZfLoginRequest            = pb.ZfLoginRequest
	ZfLoginResponse           = pb.ZfLoginResponse
	ZfSessionTermRequest      = pb.ZfSessionTermRequest

	WorkerZfService interface {
		ZfLogin(ctx context.Context, in *ZfLoginRequest, opts ...grpc.CallOption) (*ZfLoginResponse, error)
		LibraryLogin(ctx context.Context, in *LibraryLoginRequest, opts ...grpc.CallOption) (*LibraryLoginResponse, error)
		GetScore(ctx context.Context, in *ZfSessionTermRequest, opts ...grpc.CallOption) (*GetScoreResponse, error)
		GetMidTermScore(ctx context.Context, in *ZfSessionTermRequest, opts ...grpc.CallOption) (*GetMidTermScoreResponse, error)
		GetClassTable(ctx context.Context, in *ZfSessionTermRequest, opts ...grpc.CallOption) (*GetClassTableResponse, error)
		GetExamInfo(ctx context.Context, in *ZfSessionTermRequest, opts ...grpc.CallOption) (*GetExamInfoResponse, error)
		GetRoomInfo(ctx context.Context, in *GetRoomInfoRequest, opts ...grpc.CallOption) (*GetRoomInfoResponse, error)
		GetBorrowHistory(ctx context.Context, in *LibrarySessionPageRequest, opts ...grpc.CallOption) (*GetBorrowHistoryResponse, error)
		GetCurrentBorrow(ctx context.Context, in *LibrarySessionPageRequest, opts ...grpc.CallOption) (*GetCurrentBorrowResponse, error)
	}

	defaultWorkerZfService struct {
		cli zrpc.Client
	}
)

func NewWorkerZfService(cli zrpc.Client) WorkerZfService {
	return &defaultWorkerZfService{
		cli: cli,
	}
}

func (m *defaultWorkerZfService) ZfLogin(ctx context.Context, in *ZfLoginRequest, opts ...grpc.CallOption) (*ZfLoginResponse, error) {
	client := pb.NewWorkerZfServiceClient(m.cli.Conn())
	return client.ZfLogin(ctx, in, opts...)
}

func (m *defaultWorkerZfService) LibraryLogin(ctx context.Context, in *LibraryLoginRequest, opts ...grpc.CallOption) (*LibraryLoginResponse, error) {
	client := pb.NewWorkerZfServiceClient(m.cli.Conn())
	return client.LibraryLogin(ctx, in, opts...)
}

func (m *defaultWorkerZfService) GetScore(ctx context.Context, in *ZfSessionTermRequest, opts ...grpc.CallOption) (*GetScoreResponse, error) {
	client := pb.NewWorkerZfServiceClient(m.cli.Conn())
	return client.GetScore(ctx, in, opts...)
}

func (m *defaultWorkerZfService) GetMidTermScore(ctx context.Context, in *ZfSessionTermRequest, opts ...grpc.CallOption) (*GetMidTermScoreResponse, error) {
	client := pb.NewWorkerZfServiceClient(m.cli.Conn())
	return client.GetMidTermScore(ctx, in, opts...)
}

func (m *defaultWorkerZfService) GetClassTable(ctx context.Context, in *ZfSessionTermRequest, opts ...grpc.CallOption) (*GetClassTableResponse, error) {
	client := pb.NewWorkerZfServiceClient(m.cli.Conn())
	return client.GetClassTable(ctx, in, opts...)
}

func (m *defaultWorkerZfService) GetExamInfo(ctx context.Context, in *ZfSessionTermRequest, opts ...grpc.CallOption) (*GetExamInfoResponse, error) {
	client := pb.NewWorkerZfServiceClient(m.cli.Conn())
	return client.GetExamInfo(ctx, in, opts...)
}

func (m *defaultWorkerZfService) GetRoomInfo(ctx context.Context, in *GetRoomInfoRequest, opts ...grpc.CallOption) (*GetRoomInfoResponse, error) {
	client := pb.NewWorkerZfServiceClient(m.cli.Conn())
	return client.GetRoomInfo(ctx, in, opts...)
}

func (m *defaultWorkerZfService) GetBorrowHistory(ctx context.Context, in *LibrarySessionPageRequest, opts ...grpc.CallOption) (*GetBorrowHistoryResponse, error) {
	client := pb.NewWorkerZfServiceClient(m.cli.Conn())
	return client.GetBorrowHistory(ctx, in, opts...)
}

func (m *defaultWorkerZfService) GetCurrentBorrow(ctx context.Context, in *LibrarySessionPageRequest, opts ...grpc.CallOption) (*GetCurrentBorrowResponse, error) {
	client := pb.NewWorkerZfServiceClient(m.cli.Conn())
	return client.GetCurrentBorrow(ctx, in, opts...)
}
