// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type BorrowedBook struct {
	Name          string `json:"name"`
	LibraryID     string `json:"libraryID"`
	LibraryPlace  string `json:"libraryPlace"`
	Time          string `json:"time"`
	ReturnTime    string `json:"returnTime"`
	RenewalsTimes string `json:"renewalsTimes"`
	OverdueTime   string `json:"overdueTime"`
}

type Exam struct {
	LessonID    string `json:"lessonID"`
	LessonName  string `json:"lessonName"`
	LessonPlace string `json:"lessonPlace"`
	ExamPlace   string `json:"examPlace"`
	ExamTime    string `json:"examTime"`
	Campus      string `json:"campus"`
	TeacherName string `json:"teacherName"`
	ClassName   string `json:"className"`
	Credits     string `json:"credits"`
	SeatNum     string `json:"seatNum"`
}

type GetBorrowHistoryResp struct {
	Books []BorrowedBook `json:"books"`
}

type GetClassTableResp struct {
	LessonsTable    []Lesson         `json:"lessonsTable"`
	PracticeLessons []PracticeLesson `json:"practiceLessons"`
	Info            StudentInfo      `json:"info"`
}

type GetCurrentBorrowResp struct {
	Books []BorrowedBook `json:"books"`
}

type GetExamInfoResp struct {
	Exams []Exam `json:"exams"`
}

type GetMidTermScoreResp struct {
	Scores []MidTermScore `json:"scores"`
}

type GetRoomInfoReq struct {
	Session  string `json:"session"`
	Year     string `json:"year"`
	Term     string `json:"term"`
	Campus   string `json:"campus"`
	Weekday  string `json:"weekday"`
	Week     string `json:"week"`
	Sections string `json:"sections"`
}

type GetRoomInfoResp struct {
	Rooms []Room `json:"rooms"`
}

type GetScoreResp struct {
	Scores []Score `json:"scores"`
}

type Lesson struct {
	ID          string `json:"id"`
	Sections    string `json:"sections"`
	LessonName  string `json:"lessonName"`
	Campus      string `json:"campus"`
	LessonPlace string `json:"lessonPlace"`
	PlaceID     string `json:"placeID"`
	TeacherName string `json:"teacherName"`
	ClassName   string `json:"className"`
	ClassID     string `json:"classID"`
	Weekday     string `json:"weekday"`
	Week        string `json:"week"`
	LessonHours string `json:"lessonHours"`
	Credits     string `json:"credits"`
	Type        string `json:"type"`
}

type LibraryBorrowReq struct {
	Session string `json:"session"`
	Page    int64  `json:"page,optional"`
}

type LibraryLoginReq struct {
	ForceRefresh bool `json:"forceRefresh,optional"`
}

type LoginResp struct {
	Session string `json:"session"`
}

type MidTermScore struct {
	Score       string `json:"score"`
	TeacherName string `json:"teacherName"`
	LessonID    string `json:"lessonID"`
	LessonName  string `json:"lessonName"`
	ClassName   string `json:"className"`
	Credits     string `json:"credits"`
}

type PracticeLesson struct {
	LessonName  string `json:"lessonName"`
	TeacherName string `json:"teacherName"`
	ClassName   string `json:"className"`
	Credits     string `json:"credits"`
}

type Room struct {
	RoomName         string `json:"roomName"`
	BuildName        string `json:"buildName"`
	RoomSize         string `json:"roomSize"`
	RoomSeats        string `json:"roomSeats"`
	RoomSeatsForExam string `json:"roomSeatsForExam"`
	Campus           string `json:"campus"`
	Type             string `json:"type"`
}

type Score struct {
	Score       string `json:"score"`
	ScorePoint  string `json:"scorePoint"`
	TeacherName string `json:"teacherName"`
	LessonID    string `json:"lessonID"`
	LessonName  string `json:"lessonName"`
	ClassName   string `json:"className"`
	Credits     string `json:"credits"`
	LessonType  string `json:"lessonType"`
	ExamType    string `json:"examType"`
	SubmitTime  string `json:"submitTime"`
	SubmitName  string `json:"submitName"`
	SchoolTerm  string `json:"schoolTerm"`
	SchoolYear  string `json:"schoolYear"`
	Key         string `json:"key"`
}

type SessionTermReq struct {
	Session string `json:"session"`
	Year    string `json:"year"`
	Term    string `json:"term"`
}

type StudentInfo struct {
	Name      string `json:"name"`
	ClassName string `json:"className"`
}

type ZfLoginReq struct {
	LoginType    string `json:"loginType,options=ZF|OAUTH"`
	ForceRefresh bool   `json:"forceRefresh,optional"`
}
