// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: api/rpc/worker.proto

package funnel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// worker 内部登录方式。
type ZfLoginType int32

const (
	ZfLoginType_ZF_LOGIN_TYPE_UNSPECIFIED ZfLoginType = 0
	ZfLoginType_ZF_LOGIN_TYPE_CAPTCHA     ZfLoginType = 1
	ZfLoginType_ZF_LOGIN_TYPE_OAUTH       ZfLoginType = 2
)

// Enum value maps for ZfLoginType.
var (
	ZfLoginType_name = map[int32]string{
		0: "ZF_LOGIN_TYPE_UNSPECIFIED",
		1: "ZF_LOGIN_TYPE_CAPTCHA",
		2: "ZF_LOGIN_TYPE_OAUTH",
	}
	ZfLoginType_value = map[string]int32{
		"ZF_LOGIN_TYPE_UNSPECIFIED": 0,
		"ZF_LOGIN_TYPE_CAPTCHA":     1,
		"ZF_LOGIN_TYPE_OAUTH":       2,
	}
)

func (x ZfLoginType) Enum() *ZfLoginType {
	p := new(ZfLoginType)
	*p = x
	return p
}

func (x ZfLoginType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ZfLoginType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_rpc_worker_proto_enumTypes[0].Descriptor()
}

func (ZfLoginType) Type() protoreflect.EnumType {
	return &file_api_rpc_worker_proto_enumTypes[0]
}

func (x ZfLoginType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ZfLoginType.Descriptor instead.
func (ZfLoginType) EnumDescriptor() ([]byte, []int) {
	return file_api_rpc_worker_proto_rawDescGZIP(), []int{0}
}

type ZfLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	LoginType     ZfLoginType            `protobuf:"varint,3,opt,name=login_type,json=loginType,proto3,enum=funnel.ZfLoginType" json:"login_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZfLoginRequest) Reset() {
	*x = ZfLoginRequest{}
	mi := &file_api_rpc_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZfLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZfLoginRequest) ProtoMessage() {}

func (x *ZfLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZfLoginRequest.ProtoReflect.Descriptor instead.
func (*ZfLoginRequest) Descriptor() ([]byte, []int) {
	return file_api_rpc_worker_proto_rawDescGZIP(), []int{0}
}

func (x *ZfLoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ZfLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ZfLoginRequest) GetLoginType() ZfLoginType {
	if x != nil {
		return x.LoginType
	}
	return ZfLoginType_ZF_LOGIN_TYPE_UNSPECIFIED
}

type ZfLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZfSession     string                 `protobuf:"bytes,1,opt,name=zf_session,json=zfSession,proto3" json:"zf_session,omitempty"`
	Route         string                 `protobuf:"bytes,2,opt,name=route,proto3" json:"route,omitempty"`
	ZfUrlFlag     string                 `protobuf:"bytes,3,opt,name=zf_url_flag,json=zfUrlFlag,proto3" json:"zf_url_flag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZfLoginResponse) Reset() {
	*x = ZfLoginResponse{}
	mi := &file_api_rpc_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZfLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZfLoginResponse) ProtoMessage() {}

func (x *ZfLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZfLoginResponse.ProtoReflect.Descriptor instead.
func (*ZfLoginResponse) Descriptor() ([]byte, []int) {
	return file_api_rpc_worker_proto_rawDescGZIP(), []int{1}
}

func (x *ZfLoginResponse) GetZfSession() string {
	if x != nil {
		return x.ZfSession
	}
	return ""
}

func (x *ZfLoginResponse) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

func (x *ZfLoginResponse) GetZfUrlFlag() string {
	if x != nil {
		return x.ZfUrlFlag
	}
	return ""
}

type LibraryLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LibraryLoginRequest) Reset() {
	*x = LibraryLoginRequest{}
	mi := &file_api_rpc_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LibraryLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LibraryLoginRequest) ProtoMessage() {}

func (x *LibraryLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LibraryLoginRequest.ProtoReflect.Descriptor instead.
func (*LibraryLoginRequest) Descriptor() ([]byte, []int) {
	return file_api_rpc_worker_proto_rawDescGZIP(), []int{2}
}

func (x *LibraryLoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LibraryLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LibraryLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LibSession    string                 `protobuf:"bytes,1,opt,name=lib_session,json=libSession,proto3" json:"lib_session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LibraryLoginResponse) Reset() {
	*x = LibraryLoginResponse{}
	mi := &file_api_rpc_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LibraryLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LibraryLoginResponse) ProtoMessage() {}

func (x *LibraryLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LibraryLoginResponse.ProtoReflect.Descriptor instead.
func (*LibraryLoginResponse) Descriptor() ([]byte, []int) {
	return file_api_rpc_worker_proto_rawDescGZIP(), []int{3}
}

func (x *LibraryLoginResponse) GetLibSession() string {
	if x != nil {
		return x.LibSession
	}
	return ""
}

type ZfSessionTermRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ZfSession string                 `protobuf:"bytes,1,opt,name=zf_session,json=zfSession,proto3" json:"zf_session,omitempty"`
	Route     string                 `protobuf:"bytes,2,opt,name=route,proto3" json:"route,omitempty"`
	ZfUrlFlag string                 `protobuf:"bytes,3,opt,name=zf_url_flag,json=zfUrlFlag,proto3" json:"zf_url_flag,omitempty"`
	// 沿用现有业务语义，支持 "全" 或具体学年。
	Year string `protobuf:"bytes,4,opt,name=year,proto3" json:"year,omitempty"`
	// 沿用现有业务语义，支持 "上" "下" "短" "全"。
	Term          string `protobuf:"bytes,5,opt,name=term,proto3" json:"term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZfSessionTermRequest) Reset() {
	*x = ZfSessionTermRequest{}
	mi := &file_api_rpc_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZfSessionTermRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZfSessionTermRequest) ProtoMessage() {}

func (x *ZfSessionTermRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZfSessionTermRequest.ProtoReflect.Descriptor instead.
func (*ZfSessionTermRequest) Descriptor() ([]byte, []int) {
	return file_api_rpc_worker_proto_rawDescGZIP(), []int{4}
}

func (x *ZfSessionTermRequest) GetZfSession() string {
	if x != nil {
		return x.ZfSession
	}
	return ""
}

func (x *ZfSessionTermRequest) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

func (x *ZfSessionTermRequest) GetZfUrlFlag() string {
	if x != nil {
		return x.ZfUrlFlag
	}
	return ""
}

func (x *ZfSessionTermRequest) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *ZfSessionTermRequest) GetTerm() string {
	if x != nil {
		return x.Term
	}
	return ""
}

type GetRoomInfoRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ZfSession string                 `protobuf:"bytes,1,opt,name=zf_session,json=zfSession,proto3" json:"zf_session,omitempty"`
	Route     string                 `protobuf:"bytes,2,opt,name=route,proto3" json:"route,omitempty"`
	ZfUrlFlag string                 `protobuf:"bytes,3,opt,name=zf_url_flag,json=zfUrlFlag,proto3" json:"zf_url_flag,omitempty"`
	Year      string                 `protobuf:"bytes,4,opt,name=year,proto3" json:"year,omitempty"`
	Term      string                 `protobuf:"bytes,5,opt,name=term,proto3" json:"term,omitempty"`
	// 支持 "朝晖" "屏峰" "莫干山"。
	Campus string `protobuf:"bytes,6,opt,name=campus,proto3" json:"campus,omitempty"`
	// 星期几，兼容现有 1/2/3... 语义。
	Weekday string `protobuf:"bytes,7,opt,name=weekday,proto3" json:"weekday,omitempty"`
	// 第几周的 2 次幂和。
	Week string `protobuf:"bytes,8,opt,name=week,proto3" json:"week,omitempty"`
	// 第几节课的 2 次幂和。
	Sections      string `protobuf:"bytes,9,opt,name=sections,proto3" json:"sections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomInfoRequest) Reset() {
	*x = GetRoomInfoRequest{}
	mi := &file_api_rpc_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomInfoRequest) ProtoMessage() {}

func (x *GetRoomInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomInfoRequest.ProtoReflect.Descriptor instead.
func (*GetRoomInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_rpc_worker_proto_rawDescGZIP(), []int{5}
}

func (x *GetRoomInfoRequest) GetZfSession() string {
	if x != nil {
		return x.ZfSession
	}
	return ""
}

func (x *GetRoomInfoRequest) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

func (x *GetRoomInfoRequest) GetZfUrlFlag() string {
	if x != nil {
		return x.ZfUrlFlag
	}
	return ""
}

func (x *GetRoomInfoRequest) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *GetRoomInfoRequest) GetTerm() string {
	if x != nil {
		return x.Term
	}
	return ""
}

func (x *GetRoomInfoRequest) GetCampus() string {
	if x != nil {
		return x.Campus
	}
	return ""
}

func (x *GetRoomInfoRequest) GetWeekday() string {
	if x != nil {
		return x.Weekday
	}
	return ""
}

func (x *GetRoomInfoRequest) GetWeek() string {
	if x != nil {
		return x.Week
	}
	return ""
}

func (x *GetRoomInfoRequest) GetSections() string {
	if x != nil {
		return x.Sections
	}
	return ""
}

type LibrarySessionPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LibSession    string                 `protobuf:"bytes,1,opt,name=lib_session,json=libSession,proto3" json:"lib_session,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LibrarySessionPageRequest) Reset() {
	*x = LibrarySessionPageRequest{}
	mi := &file_api_rpc_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LibrarySessionPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LibrarySessionPageRequest) ProtoMessage() {}

func (x *LibrarySessionPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LibrarySessionPageRequest.ProtoReflect.Descriptor instead.
func (*LibrarySessionPageRequest) Descriptor() ([]byte, []int) {
	return file_api_rpc_worker_proto_rawDescGZIP(), []int{6}
}

func (x *LibrarySessionPageRequest) GetLibSession() string {
	if x != nil {
		return x.LibSession
	}
	return ""
}

func (x *LibrarySessionPageRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type GetScoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scores        []*Score               `protobuf:"bytes,1,rep,name=scores,proto3" json:"scores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScoreResponse) Reset() {
	*x = GetScoreResponse{}
	mi := &file_api_rpc_worker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScoreResponse) ProtoMessage() {}

func (x *GetScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_worker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScoreResponse.ProtoReflect.Descriptor instead.
func (*GetScoreResponse) Descriptor() ([]byte, []int) {
	return file_api_rpc_worker_proto_rawDescGZIP(), []int{7}
}

func (x *GetScoreResponse) GetScores() []*Score {
	if x != nil {
		return x.Scores
	}
	return nil
}

type GetMidTermScoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scores        []*MidTermScore        `protobuf:"bytes,1,rep,name=scores,proto3" json:"scores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMidTermScoreResponse) Reset() {
	*x = GetMidTermScoreResponse{}
	mi := &file_api_rpc_worker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMidTermScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMidTermScoreResponse) ProtoMessage() {}

func (x *GetMidTermScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_worker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMidTermScoreResponse.ProtoReflect.Descriptor instead.
func (*GetMidTermScoreResponse) Descriptor() ([]byte, []int) {
	return file_api_rpc_worker_proto_rawDescGZIP(), []int{8}
}

func (x *GetMidTermScoreResponse) GetScores() []*MidTermScore {
	if x != nil {
		return x.Scores
	}
	return nil
}

type GetClassTableResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LessonsTable    []*Lesson              `protobuf:"bytes,1,rep,name=lessons_table,json=lessonsTable,proto3" json:"lessons_table,omitempty"`
	PracticeLessons []*PracticeLesson      `protobuf:"bytes,2,rep,name=practice_lessons,json=practiceLessons,proto3" json:"practice_lessons,omitempty"`
	Info            *StudentInfo           `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetClassTableResponse) Reset() {
	*x = GetClassTableResponse{}
	mi := &file_api_rpc_worker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClassTableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClassTableResponse) ProtoMessage() {}

func (x *GetClassTableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_worker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClassTableResponse.ProtoReflect.Descriptor instead.
func (*GetClassTableResponse) Descriptor() ([]byte, []int) {
	return file_api_rpc_worker_proto_rawDescGZIP(), []int{9}
}

func (x *GetClassTableResponse) GetLessonsTable() []*Lesson {
	if x != nil {
		return x.LessonsTable
	}
	return nil
}

func (x *GetClassTableResponse) GetPracticeLessons() []*PracticeLesson {
	if x != nil {
		return x.PracticeLessons
	}
	return nil
}

func (x *GetClassTableResponse) GetInfo() *StudentInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type GetExamInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exams         []*Exam                `protobuf:"bytes,1,rep,name=exams,proto3" json:"exams,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExamInfoResponse) Reset() {
	*x = GetExamInfoResponse{}
	mi := &file_api_rpc_worker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExamInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExamInfoResponse) ProtoMessage() {}

func (x *GetExamInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_worker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExamInfoResponse.ProtoReflect.Descriptor instead.
func (*GetExamInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_rpc_worker_proto_rawDescGZIP(), []int{10}
}

func (x *GetExamInfoResponse) GetExams() []*Exam {
	if x != nil {
		return x.Exams
	}
	return nil
}

type GetRoomInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*Room                `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomInfoResponse) Reset() {
	*x = GetRoomInfoResponse{}
	mi := &file_api_rpc_worker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomInfoResponse) ProtoMessage() {}

func (x *GetRoomInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_worker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomInfoResponse.ProtoReflect.Descriptor instead.
func (*GetRoomInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_rpc_worker_proto_rawDescGZIP(), []int{11}
}

func (x *GetRoomInfoResponse) GetRooms() []*Room {
	if x != nil {
		return x.Rooms
	}
	return nil
}

type GetBorrowHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Books         []*BorrowedBook        `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBorrowHistoryResponse) Reset() {
	*x = GetBorrowHistoryResponse{}
	mi := &file_api_rpc_worker_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBorrowHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBorrowHistoryResponse) ProtoMessage() {}

func (x *GetBorrowHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_worker_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBorrowHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetBorrowHistoryResponse) Descriptor() ([]byte, []int) {
	return file_api_rpc_worker_proto_rawDescGZIP(), []int{12}
}

func (x *GetBorrowHistoryResponse) GetBooks() []*BorrowedBook {
	if x != nil {
		return x.Books
	}
	return nil
}

type GetCurrentBorrowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Books         []*BorrowedBook        `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentBorrowResponse) Reset() {
	*x = GetCurrentBorrowResponse{}
	mi := &file_api_rpc_worker_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentBorrowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentBorrowResponse) ProtoMessage() {}

func (x *GetCurrentBorrowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_worker_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentBorrowResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentBorrowResponse) Descriptor() ([]byte, []int) {
	return file_api_rpc_worker_proto_rawDescGZIP(), []int{13}
}

func (x *GetCurrentBorrowResponse) GetBooks() []*BorrowedBook {
	if x != nil {
		return x.Books
	}
	return nil
}

type StudentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ClassName     string                 `protobuf:"bytes,2,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentInfo) Reset() {
	*x = StudentInfo{}
	mi := &file_api_rpc_worker_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentInfo) ProtoMessage() {}

func (x *StudentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_worker_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentInfo.ProtoReflect.Descriptor instead.
func (*StudentInfo) Descriptor() ([]byte, []int) {
	return file_api_rpc_worker_proto_rawDescGZIP(), []int{14}
}

func (x *StudentInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StudentInfo) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

type Score struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         string                 `protobuf:"bytes,1,opt,name=score,proto3" json:"score,omitempty"`
	ScorePoint    string                 `protobuf:"bytes,2,opt,name=score_point,json=scorePoint,proto3" json:"score_point,omitempty"`
	TeacherName   string                 `protobuf:"bytes,3,opt,name=teacher_name,json=teacherName,proto3" json:"teacher_name,omitempty"`
	LessonId      string                 `protobuf:"bytes,4,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	LessonName    string                 `protobuf:"bytes,5,opt,name=lesson_name,json=lessonName,proto3" json:"lesson_name,omitempty"`
	ClassName     string                 `protobuf:"bytes,6,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	Credits       string                 `protobuf:"bytes,7,opt,name=credits,proto3" json:"credits,omitempty"`
	LessonType    string                 `protobuf:"bytes,8,opt,name=lesson_type,json=lessonType,proto3" json:"lesson_type,omitempty"`
	ExamType      string                 `protobuf:"bytes,9,opt,name=exam_type,json=examType,proto3" json:"exam_type,omitempty"`
	SubmitTime    string                 `protobuf:"bytes,10,opt,name=submit_time,json=submitTime,proto3" json:"submit_time,omitempty"`
	SubmitName    string                 `protobuf:"bytes,11,opt,name=submit_name,json=submitName,proto3" json:"submit_name,omitempty"`
	SchoolTerm    string                 `protobuf:"bytes,12,opt,name=school_term,json=schoolTerm,proto3" json:"school_term,omitempty"`
	SchoolYear    string                 `protobuf:"bytes,13,opt,name=school_year,json=schoolYear,proto3" json:"school_year,omitempty"`
	Key           string                 `protobuf:"bytes,14,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Score) Reset() {
	*x = Score{}
	mi := &file_api_rpc_worker_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Score) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Score) ProtoMessage() {}

func (x *Score) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_worker_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Score.ProtoReflect.Descriptor instead.
func (*Score) Descriptor() ([]byte, []int) {
	return file_api_rpc_worker_proto_rawDescGZIP(), []int{15}
}

func (x *Score) GetScore() string {
	if x != nil {
		return x.Score
	}
	return ""
}

func (x *Score) GetScorePoint() string {
	if x != nil {
		return x.ScorePoint
	}
	return ""
}

func (x *Score) GetTeacherName() string {
	if x != nil {
		return x.TeacherName
	}
	return ""
}

func (x *Score) GetLessonId() string {
	if x != nil {
		return x.LessonId
	}
	return ""
}

func (x *Score) GetLessonName() string {
	if x != nil {
		return x.LessonName
	}
	return ""
}

func (x *Score) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *Score) GetCredits() string {
	if x != nil {
		return x.Credits
	}
	return ""
}

func (x *Score) GetLessonType() string {
	if x != nil {
		return x.LessonType
	}
	return ""
}

func (x *Score) GetExamType() string {
	if x != nil {
		return x.ExamType
	}
	return ""
}

func (x *Score) GetSubmitTime() string {
	if x != nil {
		return x.SubmitTime
	}
	return ""
}

func (x *Score) GetSubmitName() string {
	if x != nil {
		return x.SubmitName
	}
	return ""
}

func (x *Score) GetSchoolTerm() string {
	if x != nil {
		return x.SchoolTerm
	}
	return ""
}

func (x *Score) GetSchoolYear() string {
	if x != nil {
		return x.SchoolYear
	}
	return ""
}

func (x *Score) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type MidTermScore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         string                 `protobuf:"bytes,1,opt,name=score,proto3" json:"score,omitempty"`
	TeacherName   string                 `protobuf:"bytes,2,opt,name=teacher_name,json=teacherName,proto3" json:"teacher_name,omitempty"`
	LessonId      string                 `protobuf:"bytes,3,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	LessonName    string                 `protobuf:"bytes,4,opt,name=lesson_name,json=lessonName,proto3" json:"lesson_name,omitempty"`
	ClassName     string                 `protobuf:"bytes,5,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	Credits       string                 `protobuf:"bytes,6,opt,name=credits,proto3" json:"credits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MidTermScore) Reset() {
	*x = MidTermScore{}
	mi := &file_api_rpc_worker_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MidTermScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MidTermScore) ProtoMessage() {}

func (x *MidTermScore) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_worker_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MidTermScore.ProtoReflect.Descriptor instead.
func (*MidTermScore) Descriptor() ([]byte, []int) {
	return file_api_rpc_worker_proto_rawDescGZIP(), []int{16}
}

func (x *MidTermScore) GetScore() string {
	if x != nil {
		return x.Score
	}
	return ""
}

func (x *MidTermScore) GetTeacherName() string {
	if x != nil {
		return x.TeacherName
	}
	return ""
}

func (x *MidTermScore) GetLessonId() string {
	if x != nil {
		return x.LessonId
	}
	return ""
}

func (x *MidTermScore) GetLessonName() string {
	if x != nil {
		return x.LessonName
	}
	return ""
}

func (x *MidTermScore) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *MidTermScore) GetCredits() string {
	if x != nil {
		return x.Credits
	}
	return ""
}

type Lesson struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Sections      string                 `protobuf:"bytes,2,opt,name=sections,proto3" json:"sections,omitempty"`
	LessonName    string                 `protobuf:"bytes,3,opt,name=lesson_name,json=lessonName,proto3" json:"lesson_name,omitempty"`
	Campus        string                 `protobuf:"bytes,4,opt,name=campus,proto3" json:"campus,omitempty"`
	LessonPlace   string                 `protobuf:"bytes,5,opt,name=lesson_place,json=lessonPlace,proto3" json:"lesson_place,omitempty"`
	PlaceId       string                 `protobuf:"bytes,6,opt,name=place_id,json=placeId,proto3" json:"place_id,omitempty"`
	TeacherName   string                 `protobuf:"bytes,7,opt,name=teacher_name,json=teacherName,proto3" json:"teacher_name,omitempty"`
	ClassName     string                 `protobuf:"bytes,8,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	ClassId       string                 `protobuf:"bytes,9,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	Weekday       string                 `protobuf:"bytes,10,opt,name=weekday,proto3" json:"weekday,omitempty"`
	Week          string                 `protobuf:"bytes,11,opt,name=week,proto3" json:"week,omitempty"`
	LessonHours   string                 `protobuf:"bytes,12,opt,name=lesson_hours,json=lessonHours,proto3" json:"lesson_hours,omitempty"`
	Credits       string                 `protobuf:"bytes,13,opt,name=credits,proto3" json:"credits,omitempty"`
	Type          string                 `protobuf:"bytes,14,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lesson) Reset() {
	*x = Lesson{}
	mi := &file_api_rpc_worker_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lesson) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lesson) ProtoMessage() {}

func (x *Lesson) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_worker_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lesson.ProtoReflect.Descriptor instead.
func (*Lesson) Descriptor() ([]byte, []int) {
	return file_api_rpc_worker_proto_rawDescGZIP(), []int{17}
}

func (x *Lesson) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Lesson) GetSections() string {
	if x != nil {
		return x.Sections
	}
	return ""
}

func (x *Lesson) GetLessonName() string {
	if x != nil {
		return x.LessonName
	}
	return ""
}

func (x *Lesson) GetCampus() string {
	if x != nil {
		return x.Campus
	}
	return ""
}

func (x *Lesson) GetLessonPlace() string {
	if x != nil {
		return x.LessonPlace
	}
	return ""
}

func (x *Lesson) GetPlaceId() string {
	if x != nil {
		return x.PlaceId
	}
	return ""
}

func (x *Lesson) GetTeacherName() string {
	if x != nil {
		return x.TeacherName
	}
	return ""
}

func (x *Lesson) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *Lesson) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

func (x *Lesson) GetWeekday() string {
	if x != nil {
		return x.Weekday
	}
	return ""
}

func (x *Lesson) GetWeek() string {
	if x != nil {
		return x.Week
	}
	return ""
}

func (x *Lesson) GetLessonHours() string {
	if x != nil {
		return x.LessonHours
	}
	return ""
}

func (x *Lesson) GetCredits() string {
	if x != nil {
		return x.Credits
	}
	return ""
}

func (x *Lesson) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type PracticeLesson struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LessonName    string                 `protobuf:"bytes,1,opt,name=lesson_name,json=lessonName,proto3" json:"lesson_name,omitempty"`
	TeacherName   string                 `protobuf:"bytes,2,opt,name=teacher_name,json=teacherName,proto3" json:"teacher_name,omitempty"`
	ClassName     string                 `protobuf:"bytes,3,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	Credits       string                 `protobuf:"bytes,4,opt,name=credits,proto3" json:"credits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PracticeLesson) Reset() {
	*x = PracticeLesson{}
	mi := &file_api_rpc_worker_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PracticeLesson) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PracticeLesson) ProtoMessage() {}

func (x *PracticeLesson) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_worker_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PracticeLesson.ProtoReflect.Descriptor instead.
func (*PracticeLesson) Descriptor() ([]byte, []int) {
	return file_api_rpc_worker_proto_rawDescGZIP(), []int{18}
}

func (x *PracticeLesson) GetLessonName() string {
	if x != nil {
		return x.LessonName
	}
	return ""
}

func (x *PracticeLesson) GetTeacherName() string {
	if x != nil {
		return x.TeacherName
	}
	return ""
}

func (x *PracticeLesson) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *PracticeLesson) GetCredits() string {
	if x != nil {
		return x.Credits
	}
	return ""
}

type Exam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LessonId      string                 `protobuf:"bytes,1,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	LessonName    string                 `protobuf:"bytes,2,opt,name=lesson_name,json=lessonName,proto3" json:"lesson_name,omitempty"`
	LessonPlace   string                 `protobuf:"bytes,3,opt,name=lesson_place,json=lessonPlace,proto3" json:"lesson_place,omitempty"`
	ExamPlace     string                 `protobuf:"bytes,4,opt,name=exam_place,json=examPlace,proto3" json:"exam_place,omitempty"`
	ExamTime      string                 `protobuf:"bytes,5,opt,name=exam_time,json=examTime,proto3" json:"exam_time,omitempty"`
	Campus        string                 `protobuf:"bytes,6,opt,name=campus,proto3" json:"campus,omitempty"`
	TeacherName   string                 `protobuf:"bytes,7,opt,name=teacher_name,json=teacherName,proto3" json:"teacher_name,omitempty"`
	ClassName     string                 `protobuf:"bytes,8,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	Credits       string                 `protobuf:"bytes,9,opt,name=credits,proto3" json:"credits,omitempty"`
	SeatNum       string                 `protobuf:"bytes,10,opt,name=seat_num,json=seatNum,proto3" json:"seat_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Exam) Reset() {
	*x = Exam{}
	mi := &file_api_rpc_worker_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exam) ProtoMessage() {}

func (x *Exam) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_worker_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exam.ProtoReflect.Descriptor instead.
func (*Exam) Descriptor() ([]byte, []int) {
	return file_api_rpc_worker_proto_rawDescGZIP(), []int{19}
}

func (x *Exam) GetLessonId() string {
	if x != nil {
		return x.LessonId
	}
	return ""
}

func (x *Exam) GetLessonName() string {
	if x != nil {
		return x.LessonName
	}
	return ""
}

func (x *Exam) GetLessonPlace() string {
	if x != nil {
		return x.LessonPlace
	}
	return ""
}

func (x *Exam) GetExamPlace() string {
	if x != nil {
		return x.ExamPlace
	}
	return ""
}

func (x *Exam) GetExamTime() string {
	if x != nil {
		return x.ExamTime
	}
	return ""
}

func (x *Exam) GetCampus() string {
	if x != nil {
		return x.Campus
	}
	return ""
}

func (x *Exam) GetTeacherName() string {
	if x != nil {
		return x.TeacherName
	}
	return ""
}

func (x *Exam) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *Exam) GetCredits() string {
	if x != nil {
		return x.Credits
	}
	return ""
}

func (x *Exam) GetSeatNum() string {
	if x != nil {
		return x.SeatNum
	}
	return ""
}

type Room struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RoomName         string                 `protobuf:"bytes,1,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	BuildName        string                 `protobuf:"bytes,2,opt,name=build_name,json=buildName,proto3" json:"build_name,omitempty"`
	RoomSize         string                 `protobuf:"bytes,3,opt,name=room_size,json=roomSize,proto3" json:"room_size,omitempty"`
	RoomSeats        string                 `protobuf:"bytes,4,opt,name=room_seats,json=roomSeats,proto3" json:"room_seats,omitempty"`
	RoomSeatsForExam string                 `protobuf:"bytes,5,opt,name=room_seats_for_exam,json=roomSeatsForExam,proto3" json:"room_seats_for_exam,omitempty"`
	Campus           string                 `protobuf:"bytes,6,opt,name=campus,proto3" json:"campus,omitempty"`
	Type             string                 `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Room) Reset() {
	*x = Room{}
	mi := &file_api_rpc_worker_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_worker_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_api_rpc_worker_proto_rawDescGZIP(), []int{20}
}

func (x *Room) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *Room) GetBuildName() string {
	if x != nil {
		return x.BuildName
	}
	return ""
}

func (x *Room) GetRoomSize() string {
	if x != nil {
		return x.RoomSize
	}
	return ""
}

func (x *Room) GetRoomSeats() string {
	if x != nil {
		return x.RoomSeats
	}
	return ""
}

func (x *Room) GetRoomSeatsForExam() string {
	if x != nil {
		return x.RoomSeatsForExam
	}
	return ""
}

func (x *Room) GetCampus() string {
	if x != nil {
		return x.Campus
	}
	return ""
}

func (x *Room) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type BorrowedBook struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	LibraryId     string                 `protobuf:"bytes,2,opt,name=library_id,json=libraryId,proto3" json:"library_id,omitempty"`
	LibraryPlace  string                 `protobuf:"bytes,3,opt,name=library_place,json=libraryPlace,proto3" json:"library_place,omitempty"`
	Time          string                 `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	ReturnTime    string                 `protobuf:"bytes,5,opt,name=return_time,json=returnTime,proto3" json:"return_time,omitempty"`
	RenewalsTimes string                 `protobuf:"bytes,6,opt,name=renewals_times,json=renewalsTimes,proto3" json:"renewals_times,omitempty"`
	OverdueTime   string                 `protobuf:"bytes,7,opt,name=overdue_time,json=overdueTime,proto3" json:"overdue_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BorrowedBook) Reset() {
	*x = BorrowedBook{}
	mi := &file_api_rpc_worker_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BorrowedBook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BorrowedBook) ProtoMessage() {}

func (x *BorrowedBook) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_worker_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BorrowedBook.ProtoReflect.Descriptor instead.
func (*BorrowedBook) Descriptor() ([]byte, []int) {
	return file_api_rpc_worker_proto_rawDescGZIP(), []int{21}
}

func (x *BorrowedBook) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BorrowedBook) GetLibraryId() string {
	if x != nil {
		return x.LibraryId
	}
	return ""
}

func (x *BorrowedBook) GetLibraryPlace() string {
	if x != nil {
		return x.LibraryPlace
	}
	return ""
}

func (x *BorrowedBook) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *BorrowedBook) GetReturnTime() string {
	if x != nil {
		return x.ReturnTime
	}
	return ""
}

func (x *BorrowedBook) GetRenewalsTimes() string {
	if x != nil {
		return x.RenewalsTimes
	}
	return ""
}

func (x *BorrowedBook) GetOverdueTime() string {
	if x != nil {
		return x.OverdueTime
	}
	return ""
}

var File_api_rpc_worker_proto protoreflect.FileDescriptor

const file_api_rpc_worker_proto_rawDesc = "" +
	"\n" +
	"\x14api/rpc/worker.proto\x12\x06funnel\"|\n" +
	"\x0eZfLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x122\n" +
	"\n" +
	"login_type\x18\x03 \x01(\x0e2\x13.funnel.ZfLoginTypeR\tloginType\"f\n" +
	"\x0fZfLoginResponse\x12\x1d\n" +
	"\n" +
	"zf_session\x18\x01 \x01(\tR\tzfSession\x12\x14\n" +
	"\x05route\x18\x02 \x01(\tR\x05route\x12\x1e\n" +
	"\vzf_url_flag\x18\x03 \x01(\tR\tzfUrlFlag\"M\n" +
	"\x13LibraryLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"7\n" +
	"\x14LibraryLoginResponse\x12\x1f\n" +
	"\vlib_session\x18\x01 \x01(\tR\n" +
	"libSession\"\x93\x01\n" +
	"\x14ZfSessionTermRequest\x12\x1d\n" +
	"\n" +
	"zf_session\x18\x01 \x01(\tR\tzfSession\x12\x14\n" +
	"\x05route\x18\x02 \x01(\tR\x05route\x12\x1e\n" +
	"\vzf_url_flag\x18\x03 \x01(\tR\tzfUrlFlag\x12\x12\n" +
	"\x04year\x18\x04 \x01(\tR\x04year\x12\x12\n" +
	"\x04term\x18\x05 \x01(\tR\x04term\"\xf3\x01\n" +
	"\x12GetRoomInfoRequest\x12\x1d\n" +
	"\n" +
	"zf_session\x18\x01 \x01(\tR\tzfSession\x12\x14\n" +
	"\x05route\x18\x02 \x01(\tR\x05route\x12\x1e\n" +
	"\vzf_url_flag\x18\x03 \x01(\tR\tzfUrlFlag\x12\x12\n" +
	"\x04year\x18\x04 \x01(\tR\x04year\x12\x12\n" +
	"\x04term\x18\x05 \x01(\tR\x04term\x12\x16\n" +
	"\x06campus\x18\x06 \x01(\tR\x06campus\x12\x18\n" +
	"\aweekday\x18\a \x01(\tR\aweekday\x12\x12\n" +
	"\x04week\x18\b \x01(\tR\x04week\x12\x1a\n" +
	"\bsections\x18\t \x01(\tR\bsections\"P\n" +
	"\x19LibrarySessionPageRequest\x12\x1f\n" +
	"\vlib_session\x18\x01 \x01(\tR\n" +
	"libSession\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\"9\n" +
	"\x10GetScoreResponse\x12%\n" +
	"\x06scores\x18\x01 \x03(\v2\r.funnel.ScoreR\x06scores\"G\n" +
	"\x17GetMidTermScoreResponse\x12,\n" +
	"\x06scores\x18\x01 \x03(\v2\x14.funnel.MidTermScoreR\x06scores\"\xb8\x01\n" +
	"\x15GetClassTableResponse\x123\n" +
	"\rlessons_table\x18\x01 \x03(\v2\x0e.funnel.LessonR\flessonsTable\x12A\n" +
	"\x10practice_lessons\x18\x02 \x03(\v2\x16.funnel.PracticeLessonR\x0fpracticeLessons\x12'\n" +
	"\x04info\x18\x03 \x01(\v2\x13.funnel.StudentInfoR\x04info\"9\n" +
	"\x13GetExamInfoResponse\x12\"\n" +
	"\x05exams\x18\x01 \x03(\v2\f.funnel.ExamR\x05exams\"9\n" +
	"\x13GetRoomInfoResponse\x12\"\n" +
	"\x05rooms\x18\x01 \x03(\v2\f.funnel.RoomR\x05rooms\"F\n" +
	"\x18GetBorrowHistoryResponse\x12*\n" +
	"\x05books\x18\x01 \x03(\v2\x14.funnel.BorrowedBookR\x05books\"F\n" +
	"\x18GetCurrentBorrowResponse\x12*\n" +
	"\x05books\x18\x01 \x03(\v2\x14.funnel.BorrowedBookR\x05books\"@\n" +
	"\vStudentInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"class_name\x18\x02 \x01(\tR\tclassName\"\xac\x03\n" +
	"\x05Score\x12\x14\n" +
	"\x05score\x18\x01 \x01(\tR\x05score\x12\x1f\n" +
	"\vscore_point\x18\x02 \x01(\tR\n" +
	"scorePoint\x12!\n" +
	"\fteacher_name\x18\x03 \x01(\tR\vteacherName\x12\x1b\n" +
	"\tlesson_id\x18\x04 \x01(\tR\blessonId\x12\x1f\n" +
	"\vlesson_name\x18\x05 \x01(\tR\n" +
	"lessonName\x12\x1d\n" +
	"\n" +
	"class_name\x18\x06 \x01(\tR\tclassName\x12\x18\n" +
	"\acredits\x18\a \x01(\tR\acredits\x12\x1f\n" +
	"\vlesson_type\x18\b \x01(\tR\n" +
	"lessonType\x12\x1b\n" +
	"\texam_type\x18\t \x01(\tR\bexamType\x12\x1f\n" +
	"\vsubmit_time\x18\n" +
	" \x01(\tR\n" +
	"submitTime\x12\x1f\n" +
	"\vsubmit_name\x18\v \x01(\tR\n" +
	"submitName\x12\x1f\n" +
	"\vschool_term\x18\f \x01(\tR\n" +
	"schoolTerm\x12\x1f\n" +
	"\vschool_year\x18\r \x01(\tR\n" +
	"schoolYear\x12\x10\n" +
	"\x03key\x18\x0e \x01(\tR\x03key\"\xbe\x01\n" +
	"\fMidTermScore\x12\x14\n" +
	"\x05score\x18\x01 \x01(\tR\x05score\x12!\n" +
	"\fteacher_name\x18\x02 \x01(\tR\vteacherName\x12\x1b\n" +
	"\tlesson_id\x18\x03 \x01(\tR\blessonId\x12\x1f\n" +
	"\vlesson_name\x18\x04 \x01(\tR\n" +
	"lessonName\x12\x1d\n" +
	"\n" +
	"class_name\x18\x05 \x01(\tR\tclassName\x12\x18\n" +
	"\acredits\x18\x06 \x01(\tR\acredits\"\x87\x03\n" +
	"\x06Lesson\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bsections\x18\x02 \x01(\tR\bsections\x12\x1f\n" +
	"\vlesson_name\x18\x03 \x01(\tR\n" +
	"lessonName\x12\x16\n" +
	"\x06campus\x18\x04 \x01(\tR\x06campus\x12!\n" +
	"\flesson_place\x18\x05 \x01(\tR\vlessonPlace\x12\x19\n" +
	"\bplace_id\x18\x06 \x01(\tR\aplaceId\x12!\n" +
	"\fteacher_name\x18\a \x01(\tR\vteacherName\x12\x1d\n" +
	"\n" +
	"class_name\x18\b \x01(\tR\tclassName\x12\x19\n" +
	"\bclass_id\x18\t \x01(\tR\aclassId\x12\x18\n" +
	"\aweekday\x18\n" +
	" \x01(\tR\aweekday\x12\x12\n" +
	"\x04week\x18\v \x01(\tR\x04week\x12!\n" +
	"\flesson_hours\x18\f \x01(\tR\vlessonHours\x12\x18\n" +
	"\acredits\x18\r \x01(\tR\acredits\x12\x12\n" +
	"\x04type\x18\x0e \x01(\tR\x04type\"\x8d\x01\n" +
	"\x0ePracticeLesson\x12\x1f\n" +
	"\vlesson_name\x18\x01 \x01(\tR\n" +
	"lessonName\x12!\n" +
	"\fteacher_name\x18\x02 \x01(\tR\vteacherName\x12\x1d\n" +
	"\n" +
	"class_name\x18\x03 \x01(\tR\tclassName\x12\x18\n" +
	"\acredits\x18\x04 \x01(\tR\acredits\"\xb2\x02\n" +
	"\x04Exam\x12\x1b\n" +
	"\tlesson_id\x18\x01 \x01(\tR\blessonId\x12\x1f\n" +
	"\vlesson_name\x18\x02 \x01(\tR\n" +
	"lessonName\x12!\n" +
	"\flesson_place\x18\x03 \x01(\tR\vlessonPlace\x12\x1d\n" +
	"\n" +
	"exam_place\x18\x04 \x01(\tR\texamPlace\x12\x1b\n" +
	"\texam_time\x18\x05 \x01(\tR\bexamTime\x12\x16\n" +
	"\x06campus\x18\x06 \x01(\tR\x06campus\x12!\n" +
	"\fteacher_name\x18\a \x01(\tR\vteacherName\x12\x1d\n" +
	"\n" +
	"class_name\x18\b \x01(\tR\tclassName\x12\x18\n" +
	"\acredits\x18\t \x01(\tR\acredits\x12\x19\n" +
	"\bseat_num\x18\n" +
	" \x01(\tR\aseatNum\"\xd9\x01\n" +
	"\x04Room\x12\x1b\n" +
	"\troom_name\x18\x01 \x01(\tR\broomName\x12\x1d\n" +
	"\n" +
	"build_name\x18\x02 \x01(\tR\tbuildName\x12\x1b\n" +
	"\troom_size\x18\x03 \x01(\tR\broomSize\x12\x1d\n" +
	"\n" +
	"room_seats\x18\x04 \x01(\tR\troomSeats\x12-\n" +
	"\x13room_seats_for_exam\x18\x05 \x01(\tR\x10roomSeatsForExam\x12\x16\n" +
	"\x06campus\x18\x06 \x01(\tR\x06campus\x12\x12\n" +
	"\x04type\x18\a \x01(\tR\x04type\"\xe5\x01\n" +
	"\fBorrowedBook\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"library_id\x18\x02 \x01(\tR\tlibraryId\x12#\n" +
	"\rlibrary_place\x18\x03 \x01(\tR\flibraryPlace\x12\x12\n" +
	"\x04time\x18\x04 \x01(\tR\x04time\x12\x1f\n" +
	"\vreturn_time\x18\x05 \x01(\tR\n" +
	"returnTime\x12%\n" +
	"\x0erenewals_times\x18\x06 \x01(\tR\rrenewalsTimes\x12!\n" +
	"\foverdue_time\x18\a \x01(\tR\voverdueTime*`\n" +
	"\vZfLoginType\x12\x1d\n" +
	"\x19ZF_LOGIN_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ZF_LOGIN_TYPE_CAPTCHA\x10\x01\x12\x17\n" +
	"\x13ZF_LOGIN_TYPE_OAUTH\x10\x022\xc0\x05\n" +
	"\x0fWorkerZfService\x12:\n" +
	"\aZfLogin\x12\x16.funnel.ZfLoginRequest\x1a\x17.funnel.ZfLoginResponse\x12I\n" +
	"\fLibraryLogin\x12\x1b.funnel.LibraryLoginRequest\x1a\x1c.funnel.LibraryLoginResponse\x12B\n" +
	"\bGetScore\x12\x1c.funnel.ZfSessionTermRequest\x1a\x18.funnel.GetScoreResponse\x12P\n" +
	"\x0fGetMidTermScore\x12\x1c.funnel.ZfSessionTermRequest\x1a\x1f.funnel.GetMidTermScoreResponse\x12L\n" +
	"\rGetClassTable\x12\x1c.funnel.ZfSessionTermRequest\x1a\x1d.funnel.GetClassTableResponse\x12H\n" +
	"\vGetExamInfo\x12\x1c.funnel.ZfSessionTermRequest\x1a\x1b.funnel.GetExamInfoResponse\x12F\n" +
	"\vGetRoomInfo\x12\x1a.funnel.GetRoomInfoRequest\x1a\x1b.funnel.GetRoomInfoResponse\x12W\n" +
	"\x10GetBorrowHistory\x12!.funnel.LibrarySessionPageRequest\x1a .funnel.GetBorrowHistoryResponse\x12W\n" +
	"\x10GetCurrentBorrow\x12!.funnel.LibrarySessionPageRequest\x1a .funnel.GetCurrentBorrowResponseB\n" +
	"Z\b./funnelb\x06proto3"

var (
	file_api_rpc_worker_proto_rawDescOnce sync.Once
	file_api_rpc_worker_proto_rawDescData []byte
)

func file_api_rpc_worker_proto_rawDescGZIP() []byte {
	file_api_rpc_worker_proto_rawDescOnce.Do(func() {
		file_api_rpc_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_rpc_worker_proto_rawDesc), len(file_api_rpc_worker_proto_rawDesc)))
	})
	return file_api_rpc_worker_proto_rawDescData
}

var file_api_rpc_worker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_rpc_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_api_rpc_worker_proto_goTypes = []any{
	(ZfLoginType)(0),                  // 0: funnel.ZfLoginType
	(*ZfLoginRequest)(nil),            // 1: funnel.ZfLoginRequest
	(*ZfLoginResponse)(nil),           // 2: funnel.ZfLoginResponse
	(*LibraryLoginRequest)(nil),       // 3: funnel.LibraryLoginRequest
	(*LibraryLoginResponse)(nil),      // 4: funnel.LibraryLoginResponse
	(*ZfSessionTermRequest)(nil),      // 5: funnel.ZfSessionTermRequest
	(*GetRoomInfoRequest)(nil),        // 6: funnel.GetRoomInfoRequest
	(*LibrarySessionPageRequest)(nil), // 7: funnel.LibrarySessionPageRequest
	(*GetScoreResponse)(nil),          // 8: funnel.GetScoreResponse
	(*GetMidTermScoreResponse)(nil),   // 9: funnel.GetMidTermScoreResponse
	(*GetClassTableResponse)(nil),     // 10: funnel.GetClassTableResponse
	(*GetExamInfoResponse)(nil),       // 11: funnel.GetExamInfoResponse
	(*GetRoomInfoResponse)(nil),       // 12: funnel.GetRoomInfoResponse
	(*GetBorrowHistoryResponse)(nil),  // 13: funnel.GetBorrowHistoryResponse
	(*GetCurrentBorrowResponse)(nil),  // 14: funnel.GetCurrentBorrowResponse
	(*StudentInfo)(nil),               // 15: funnel.StudentInfo
	(*Score)(nil),                     // 16: funnel.Score
	(*MidTermScore)(nil),              // 17: funnel.MidTermScore
	(*Lesson)(nil),                    // 18: funnel.Lesson
	(*PracticeLesson)(nil),            // 19: funnel.PracticeLesson
	(*Exam)(nil),                      // 20: funnel.Exam
	(*Room)(nil),                      // 21: funnel.Room
	(*BorrowedBook)(nil),              // 22: funnel.BorrowedBook
}
var file_api_rpc_worker_proto_depIdxs = []int32{
	0,  // 0: funnel.ZfLoginRequest.login_type:type_name -> funnel.ZfLoginType
	16, // 1: funnel.GetScoreResponse.scores:type_name -> funnel.Score
	17, // 2: funnel.GetMidTermScoreResponse.scores:type_name -> funnel.MidTermScore
	18, // 3: funnel.GetClassTableResponse.lessons_table:type_name -> funnel.Lesson
	19, // 4: funnel.GetClassTableResponse.practice_lessons:type_name -> funnel.PracticeLesson
	15, // 5: funnel.GetClassTableResponse.info:type_name -> funnel.StudentInfo
	20, // 6: funnel.GetExamInfoResponse.exams:type_name -> funnel.Exam
	21, // 7: funnel.GetRoomInfoResponse.rooms:type_name -> funnel.Room
	22, // 8: funnel.GetBorrowHistoryResponse.books:type_name -> funnel.BorrowedBook
	22, // 9: funnel.GetCurrentBorrowResponse.books:type_name -> funnel.BorrowedBook
	1,  // 10: funnel.WorkerZfService.ZfLogin:input_type -> funnel.ZfLoginRequest
	3,  // 11: funnel.WorkerZfService.LibraryLogin:input_type -> funnel.LibraryLoginRequest
	5,  // 12: funnel.WorkerZfService.GetScore:input_type -> funnel.ZfSessionTermRequest
	5,  // 13: funnel.WorkerZfService.GetMidTermScore:input_type -> funnel.ZfSessionTermRequest
	5,  // 14: funnel.WorkerZfService.GetClassTable:input_type -> funnel.ZfSessionTermRequest
	5,  // 15: funnel.WorkerZfService.GetExamInfo:input_type -> funnel.ZfSessionTermRequest
	6,  // 16: funnel.WorkerZfService.GetRoomInfo:input_type -> funnel.GetRoomInfoRequest
	7,  // 17: funnel.WorkerZfService.GetBorrowHistory:input_type -> funnel.LibrarySessionPageRequest
	7,  // 18: funnel.WorkerZfService.GetCurrentBorrow:input_type -> funnel.LibrarySessionPageRequest
	2,  // 19: funnel.WorkerZfService.ZfLogin:output_type -> funnel.ZfLoginResponse
	4,  // 20: funnel.WorkerZfService.LibraryLogin:output_type -> funnel.LibraryLoginResponse
	8,  // 21: funnel.WorkerZfService.GetScore:output_type -> funnel.GetScoreResponse
	9,  // 22: funnel.WorkerZfService.GetMidTermScore:output_type -> funnel.GetMidTermScoreResponse
	10, // 23: funnel.WorkerZfService.GetClassTable:output_type -> funnel.GetClassTableResponse
	11, // 24: funnel.WorkerZfService.GetExamInfo:output_type -> funnel.GetExamInfoResponse
	12, // 25: funnel.WorkerZfService.GetRoomInfo:output_type -> funnel.GetRoomInfoResponse
	13, // 26: funnel.WorkerZfService.GetBorrowHistory:output_type -> funnel.GetBorrowHistoryResponse
	14, // 27: funnel.WorkerZfService.GetCurrentBorrow:output_type -> funnel.GetCurrentBorrowResponse
	19, // [19:28] is the sub-list for method output_type
	10, // [10:19] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_api_rpc_worker_proto_init() }
func file_api_rpc_worker_proto_init() {
	if File_api_rpc_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_rpc_worker_proto_rawDesc), len(file_api_rpc_worker_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_rpc_worker_proto_goTypes,
		DependencyIndexes: file_api_rpc_worker_proto_depIdxs,
		EnumInfos:         file_api_rpc_worker_proto_enumTypes,
		MessageInfos:      file_api_rpc_worker_proto_msgTypes,
	}.Build()
	File_api_rpc_worker_proto = out.File
	file_api_rpc_worker_proto_goTypes = nil
	file_api_rpc_worker_proto_depIdxs = nil
}
