// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.0
// source: api/rpc/worker.proto

package funnel

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkerZfService_ZfLogin_FullMethodName          = "/funnel.WorkerZfService/ZfLogin"
	WorkerZfService_LibraryLogin_FullMethodName     = "/funnel.WorkerZfService/LibraryLogin"
	WorkerZfService_GetScore_FullMethodName         = "/funnel.WorkerZfService/GetScore"
	WorkerZfService_GetMidTermScore_FullMethodName  = "/funnel.WorkerZfService/GetMidTermScore"
	WorkerZfService_GetClassTable_FullMethodName    = "/funnel.WorkerZfService/GetClassTable"
	WorkerZfService_GetExamInfo_FullMethodName      = "/funnel.WorkerZfService/GetExamInfo"
	WorkerZfService_GetRoomInfo_FullMethodName      = "/funnel.WorkerZfService/GetRoomInfo"
	WorkerZfService_GetBorrowHistory_FullMethodName = "/funnel.WorkerZfService/GetBorrowHistory"
	WorkerZfService_GetCurrentBorrow_FullMethodName = "/funnel.WorkerZfService/GetCurrentBorrow"
)

// WorkerZfServiceClient is the client API for WorkerZfService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkerZfServiceClient interface {
	ZfLogin(ctx context.Context, in *ZfLoginRequest, opts ...grpc.CallOption) (*ZfLoginResponse, error)
	LibraryLogin(ctx context.Context, in *LibraryLoginRequest, opts ...grpc.CallOption) (*LibraryLoginResponse, error)
	GetScore(ctx context.Context, in *ZfSessionTermRequest, opts ...grpc.CallOption) (*GetScoreResponse, error)
	GetMidTermScore(ctx context.Context, in *ZfSessionTermRequest, opts ...grpc.CallOption) (*GetMidTermScoreResponse, error)
	GetClassTable(ctx context.Context, in *ZfSessionTermRequest, opts ...grpc.CallOption) (*GetClassTableResponse, error)
	GetExamInfo(ctx context.Context, in *ZfSessionTermRequest, opts ...grpc.CallOption) (*GetExamInfoResponse, error)
	GetRoomInfo(ctx context.Context, in *GetRoomInfoRequest, opts ...grpc.CallOption) (*GetRoomInfoResponse, error)
	GetBorrowHistory(ctx context.Context, in *LibrarySessionPageRequest, opts ...grpc.CallOption) (*GetBorrowHistoryResponse, error)
	GetCurrentBorrow(ctx context.Context, in *LibrarySessionPageRequest, opts ...grpc.CallOption) (*GetCurrentBorrowResponse, error)
}

type workerZfServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerZfServiceClient(cc grpc.ClientConnInterface) WorkerZfServiceClient {
	return &workerZfServiceClient{cc}
}

func (c *workerZfServiceClient) ZfLogin(ctx context.Context, in *ZfLoginRequest, opts ...grpc.CallOption) (*ZfLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ZfLoginResponse)
	err := c.cc.Invoke(ctx, WorkerZfService_ZfLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerZfServiceClient) LibraryLogin(ctx context.Context, in *LibraryLoginRequest, opts ...grpc.CallOption) (*LibraryLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LibraryLoginResponse)
	err := c.cc.Invoke(ctx, WorkerZfService_LibraryLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerZfServiceClient) GetScore(ctx context.Context, in *ZfSessionTermRequest, opts ...grpc.CallOption) (*GetScoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetScoreResponse)
	err := c.cc.Invoke(ctx, WorkerZfService_GetScore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerZfServiceClient) GetMidTermScore(ctx context.Context, in *ZfSessionTermRequest, opts ...grpc.CallOption) (*GetMidTermScoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMidTermScoreResponse)
	err := c.cc.Invoke(ctx, WorkerZfService_GetMidTermScore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerZfServiceClient) GetClassTable(ctx context.Context, in *ZfSessionTermRequest, opts ...grpc.CallOption) (*GetClassTableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClassTableResponse)
	err := c.cc.Invoke(ctx, WorkerZfService_GetClassTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerZfServiceClient) GetExamInfo(ctx context.Context, in *ZfSessionTermRequest, opts ...grpc.CallOption) (*GetExamInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExamInfoResponse)
	err := c.cc.Invoke(ctx, WorkerZfService_GetExamInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerZfServiceClient) GetRoomInfo(ctx context.Context, in *GetRoomInfoRequest, opts ...grpc.CallOption) (*GetRoomInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoomInfoResponse)
	err := c.cc.Invoke(ctx, WorkerZfService_GetRoomInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerZfServiceClient) GetBorrowHistory(ctx context.Context, in *LibrarySessionPageRequest, opts ...grpc.CallOption) (*GetBorrowHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBorrowHistoryResponse)
	err := c.cc.Invoke(ctx, WorkerZfService_GetBorrowHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerZfServiceClient) GetCurrentBorrow(ctx context.Context, in *LibrarySessionPageRequest, opts ...grpc.CallOption) (*GetCurrentBorrowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCurrentBorrowResponse)
	err := c.cc.Invoke(ctx, WorkerZfService_GetCurrentBorrow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerZfServiceServer is the server API for WorkerZfService service.
// All implementations must embed UnimplementedWorkerZfServiceServer
// for forward compatibility.
type WorkerZfServiceServer interface {
	ZfLogin(context.Context, *ZfLoginRequest) (*ZfLoginResponse, error)
	LibraryLogin(context.Context, *LibraryLoginRequest) (*LibraryLoginResponse, error)
	GetScore(context.Context, *ZfSessionTermRequest) (*GetScoreResponse, error)
	GetMidTermScore(context.Context, *ZfSessionTermRequest) (*GetMidTermScoreResponse, error)
	GetClassTable(context.Context, *ZfSessionTermRequest) (*GetClassTableResponse, error)
	GetExamInfo(context.Context, *ZfSessionTermRequest) (*GetExamInfoResponse, error)
	GetRoomInfo(context.Context, *GetRoomInfoRequest) (*GetRoomInfoResponse, error)
	GetBorrowHistory(context.Context, *LibrarySessionPageRequest) (*GetBorrowHistoryResponse, error)
	GetCurrentBorrow(context.Context, *LibrarySessionPageRequest) (*GetCurrentBorrowResponse, error)
	mustEmbedUnimplementedWorkerZfServiceServer()
}

// UnimplementedWorkerZfServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerZfServiceServer struct{}

func (UnimplementedWorkerZfServiceServer) ZfLogin(context.Context, *ZfLoginRequest) (*ZfLoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ZfLogin not implemented")
}
func (UnimplementedWorkerZfServiceServer) LibraryLogin(context.Context, *LibraryLoginRequest) (*LibraryLoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LibraryLogin not implemented")
}
func (UnimplementedWorkerZfServiceServer) GetScore(context.Context, *ZfSessionTermRequest) (*GetScoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetScore not implemented")
}
func (UnimplementedWorkerZfServiceServer) GetMidTermScore(context.Context, *ZfSessionTermRequest) (*GetMidTermScoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMidTermScore not implemented")
}
func (UnimplementedWorkerZfServiceServer) GetClassTable(context.Context, *ZfSessionTermRequest) (*GetClassTableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClassTable not implemented")
}
func (UnimplementedWorkerZfServiceServer) GetExamInfo(context.Context, *ZfSessionTermRequest) (*GetExamInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExamInfo not implemented")
}
func (UnimplementedWorkerZfServiceServer) GetRoomInfo(context.Context, *GetRoomInfoRequest) (*GetRoomInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRoomInfo not implemented")
}
func (UnimplementedWorkerZfServiceServer) GetBorrowHistory(context.Context, *LibrarySessionPageRequest) (*GetBorrowHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBorrowHistory not implemented")
}
func (UnimplementedWorkerZfServiceServer) GetCurrentBorrow(context.Context, *LibrarySessionPageRequest) (*GetCurrentBorrowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCurrentBorrow not implemented")
}
func (UnimplementedWorkerZfServiceServer) mustEmbedUnimplementedWorkerZfServiceServer() {}
func (UnimplementedWorkerZfServiceServer) testEmbeddedByValue()                         {}

// UnsafeWorkerZfServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerZfServiceServer will
// result in compilation errors.
type UnsafeWorkerZfServiceServer interface {
	mustEmbedUnimplementedWorkerZfServiceServer()
}

func RegisterWorkerZfServiceServer(s grpc.ServiceRegistrar, srv WorkerZfServiceServer) {
	// If the following call panics, it indicates UnimplementedWorkerZfServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkerZfService_ServiceDesc, srv)
}

func _WorkerZfService_ZfLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZfLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerZfServiceServer).ZfLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerZfService_ZfLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerZfServiceServer).ZfLogin(ctx, req.(*ZfLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerZfService_LibraryLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LibraryLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerZfServiceServer).LibraryLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerZfService_LibraryLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerZfServiceServer).LibraryLogin(ctx, req.(*LibraryLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerZfService_GetScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZfSessionTermRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerZfServiceServer).GetScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerZfService_GetScore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerZfServiceServer).GetScore(ctx, req.(*ZfSessionTermRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerZfService_GetMidTermScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZfSessionTermRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerZfServiceServer).GetMidTermScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerZfService_GetMidTermScore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerZfServiceServer).GetMidTermScore(ctx, req.(*ZfSessionTermRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerZfService_GetClassTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZfSessionTermRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerZfServiceServer).GetClassTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerZfService_GetClassTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerZfServiceServer).GetClassTable(ctx, req.(*ZfSessionTermRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerZfService_GetExamInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZfSessionTermRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerZfServiceServer).GetExamInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerZfService_GetExamInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerZfServiceServer).GetExamInfo(ctx, req.(*ZfSessionTermRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerZfService_GetRoomInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoomInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerZfServiceServer).GetRoomInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerZfService_GetRoomInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerZfServiceServer).GetRoomInfo(ctx, req.(*GetRoomInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerZfService_GetBorrowHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LibrarySessionPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerZfServiceServer).GetBorrowHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerZfService_GetBorrowHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerZfServiceServer).GetBorrowHistory(ctx, req.(*LibrarySessionPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerZfService_GetCurrentBorrow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LibrarySessionPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerZfServiceServer).GetCurrentBorrow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerZfService_GetCurrentBorrow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerZfServiceServer).GetCurrentBorrow(ctx, req.(*LibrarySessionPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkerZfService_ServiceDesc is the grpc.ServiceDesc for WorkerZfService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerZfService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "funnel.WorkerZfService",
	HandlerType: (*WorkerZfServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ZfLogin",
			Handler:    _WorkerZfService_ZfLogin_Handler,
		},
		{
			MethodName: "LibraryLogin",
			Handler:    _WorkerZfService_LibraryLogin_Handler,
		},
		{
			MethodName: "GetScore",
			Handler:    _WorkerZfService_GetScore_Handler,
		},
		{
			MethodName: "GetMidTermScore",
			Handler:    _WorkerZfService_GetMidTermScore_Handler,
		},
		{
			MethodName: "GetClassTable",
			Handler:    _WorkerZfService_GetClassTable_Handler,
		},
		{
			MethodName: "GetExamInfo",
			Handler:    _WorkerZfService_GetExamInfo_Handler,
		},
		{
			MethodName: "GetRoomInfo",
			Handler:    _WorkerZfService_GetRoomInfo_Handler,
		},
		{
			MethodName: "GetBorrowHistory",
			Handler:    _WorkerZfService_GetBorrowHistory_Handler,
		},
		{
			MethodName: "GetCurrentBorrow",
			Handler:    _WorkerZfService_GetCurrentBorrow_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/rpc/worker.proto",
}
