// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: funnel.proto

package server

import (
	"context"

	"funnel/apps/funnel-rpc/internal/logic"
	"funnel/apps/funnel-rpc/internal/svc"
	"funnel/apps/funnel-rpc/pb"
)

type WorkerZfServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedWorkerZfServiceServer
}

func NewWorkerZfServiceServer(svcCtx *svc.ServiceContext) *WorkerZfServiceServer {
	return &WorkerZfServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *WorkerZfServiceServer) ZfLogin(ctx context.Context, in *pb.ZfLoginRequest) (*pb.ZfLoginResponse, error) {
	l := logic.NewZfLoginLogic(ctx, s.svcCtx)
	return l.ZfLogin(in)
}

func (s *WorkerZfServiceServer) LibraryLogin(ctx context.Context, in *pb.LibraryLoginRequest) (*pb.LibraryLoginResponse, error) {
	l := logic.NewLibraryLoginLogic(ctx, s.svcCtx)
	return l.LibraryLogin(in)
}

func (s *WorkerZfServiceServer) GetScore(ctx context.Context, in *pb.ZfSessionTermRequest) (*pb.GetScoreResponse, error) {
	l := logic.NewGetScoreLogic(ctx, s.svcCtx)
	return l.GetScore(in)
}

func (s *WorkerZfServiceServer) GetMidTermScore(ctx context.Context, in *pb.ZfSessionTermRequest) (*pb.GetMidTermScoreResponse, error) {
	l := logic.NewGetMidTermScoreLogic(ctx, s.svcCtx)
	return l.GetMidTermScore(in)
}

func (s *WorkerZfServiceServer) GetClassTable(ctx context.Context, in *pb.ZfSessionTermRequest) (*pb.GetClassTableResponse, error) {
	l := logic.NewGetClassTableLogic(ctx, s.svcCtx)
	return l.GetClassTable(in)
}

func (s *WorkerZfServiceServer) GetExamInfo(ctx context.Context, in *pb.ZfSessionTermRequest) (*pb.GetExamInfoResponse, error) {
	l := logic.NewGetExamInfoLogic(ctx, s.svcCtx)
	return l.GetExamInfo(in)
}

func (s *WorkerZfServiceServer) GetRoomInfo(ctx context.Context, in *pb.GetRoomInfoRequest) (*pb.GetRoomInfoResponse, error) {
	l := logic.NewGetRoomInfoLogic(ctx, s.svcCtx)
	return l.GetRoomInfo(in)
}

func (s *WorkerZfServiceServer) GetBorrowHistory(ctx context.Context, in *pb.LibrarySessionPageRequest) (*pb.GetBorrowHistoryResponse, error) {
	l := logic.NewGetBorrowHistoryLogic(ctx, s.svcCtx)
	return l.GetBorrowHistory(in)
}

func (s *WorkerZfServiceServer) GetCurrentBorrow(ctx context.Context, in *pb.LibrarySessionPageRequest) (*pb.GetCurrentBorrowResponse, error) {
	l := logic.NewGetCurrentBorrowLogic(ctx, s.svcCtx)
	return l.GetCurrentBorrow(in)
}
